### ISSUE TITLE
Is there some way to have "Surprise me" run on VS Code startup?

### ISSUE THREAD

**Issue by Nivmorabin** [johnpapa/vscode-peacock#81] opened 2019-03-11 13:49 UTC
Hi, great extension :)

Some option I miss is the ability to run Surprise me on whenever I start a new VS Code instance (maybe I missed it?).

So I downloaded [Auto run command](https://marketplace.visualstudio.com/items?itemName=gabrielgrinberg.auto-run-command) to run it on my own but couldn't find a way to call changeColorToRandomHandler().

Into what > "Peacock: Surprise me with a Random color" translated? peacock.changeColorToRandomHandler() doesn't work.

Thanks ahead,

Niv

**Comment by johnpapa** [comment] 2019-03-11 15:09
closing as a duplicate of #33

**Closed by johnpapa** 2019-03-11 15:09 UTC
