### ISSUE TITLE
Peacock on OpenSuse

### ISSUE THREAD

**Issue by Blyvion** [johnpapa/vscode-peacock#439] opened 2021-04-05 19:29 UTC
Error: (OVP_00009)
Brower: Mozilla Firefox
OS: OpenSuse (linux)
Monitor connection: Display Port (required for 144hz)

**Comment by johnpapa** [comment] 2021-04-05 19:29
Thank you @Blyvion for creating this issue!

**Comment by johnpapa** [comment] 2021-04-26 01:18
Closing due to lack of details. If you can provide details on what you are experiencing, how to reproduce, and what you want to happen, please do so and re-open.

**Closed by johnpapa** 2021-04-26 01:18 UTC

**Comment by xirtamehtsitahw** [comment] 2022-04-20 03:48
Getting persistent ovp_00009 errors from Peacock, and similar refuse-to-work issues on HBO Max and Hulu as well. How is it that all these streaming services are so willing to take my money, yet refuse to work? It reeks of a scam.

**Comment by willpower232** [comment] 2022-04-20 08:46
@xirtamehtsitahw wrong peacock repo I'm afraid
