### ISSUE TITLE
ColorCustomizations reset when opening a workspace

### ISSUE THREAD

**Issue by MFueg** [johnpapa/vscode-peacock#262] opened 2019-08-20 05:58 UTC
**Versions:**

- OS: Windows 10 
- VS Code version 1.37.1 (user setup)
- Peacock Version 3.1.1

**Description**
In my workspace settings I use colors generated with the peacock extension. Great so far!
But in my case I only use the `titleBar.*` properties and removed the ones for the `activityBar .*` and `statusBar.*`.

The workspace file should look like this example:
```
{
  "workbench.colorCustomizations": {
    "titleBar.activeBackground": "#c39533",
    "titleBar.inactiveBackground": "#c3953399",
    "titleBar.activeForeground": "#15202b",
    "titleBar.inactiveForeground": "#15202b99"
  },
  "peacock.color": "#c39533"
}
```

But everytime you launch VS Code or switch the workspace, the extension recreates the "missing" color settings in the workspace file.

![image](https://user-images.githubusercontent.com/47006140/63320383-e7af3d00-c31d-11e9-9df1-9728ad6157c1.png)

**To Reproduce**

1. Open the workspace file
2. Remove one of the `workbench.colorCustomizations` entries
3. Save the workspace file
4. Reopen the workspace or restart VS Code
5. Now your color-changes will be resetted

**Comment by johnpapa** [comment] 2019-08-21 15:54
Hi, thanks for creating the issue. Can you share what your user settings are for Peacock?

Peacock uses these three settings to determine which elements to color:

```
    "peacock.affectActivityBar": true,
    "peacock.affectStatusBar": true,
    "peacock.affectTitleBar": true,
```

If any of those are true, they will be colored.

You can learn more about these and other [affected settings in the guide here](https://papapeacockstorage.z13.web.core.windows.net/guide/#affected-elements).

Once you share your settings, we can see if this is the cause or if something else is at play here.

**Comment by MFueg** [comment] 2019-08-22 05:25
Hi,

thanks for the hint!

Those properties you've mentioned had their default values.

## My Settings
The property I had changed was `peacock.favoriteColors`.

All peacock properties of my user settings:
```
"peacock.favoriteColors": [
    {
      "name": "Angular Red",
      "value": "#b52e31"
    }
  ],
```

All peacock properties of my workspace settings:
```
"peacock.color": "#17c79c",
```

## Solution: Setting the `affects*`-properties

Setting the `affects*`-properties to:
```
  "peacock.affectAccentBorders": false,
  "peacock.affectStatusBar": false,
  "peacock.affectTitleBar": true,
  "peacock.affectActivityBar": false
```
works as charm ✔️ .

Thanks!

## New problem? Setting all  `affects*`-properties to `false`

During my tests I once set all of the properties to false.
Then peacock resets all my workspace color-customizations instead of keeping the ones I've defined.
I don't know if it is a problem.

For me it is ok setting only the `affectTitleBar` to `true`

**Comment by johnpapa** [comment] 2019-08-22 12:19
Please open a new issue and describe the problem. 

Thanks

Closing this one as it works as designed and as per the docs

**Closed by johnpapa** 2019-08-22 12:19 UTC
