### ISSUE TITLE
Don't create workspace settings.json unless a color is chosen

### ISSUE THREAD

**Issue by kbd** [johnpapa/vscode-peacock#226] opened 2019-07-26 22:20 UTC
If Peacock is disabled and I open VSCode, no workspace folder is created:

```
$ ls -a
./  ../
$ code .
$ ls -a
./  ../
```

If Peacock is enabled (even with `"peacock.surpriseMeOnStartup": false`), it creates a workspace folder with default settings:

```
$ ls -a
./  ../
$ code .
$ ls -a
./  ../  .vscode/
$ bat --style=header .vscode/*
File: .vscode/settings.json
{
    "workbench.colorCustomizations": {
        "editor.selectionBackground": "#888",
        "editor.selectionHighlightBackground": "#555",
        "editor.findMatchHighlightBackground": "#2cdd1c65",
        "editorIndentGuide.activeBackground": "#888",
        "titleBar.activeBackground": "#777777",
        "titleBar.inactiveBackground": "#77777799",
        "titleBar.activeForeground": "#e7e7e7",
        "titleBar.inactiveForeground": "#e7e7e799",
        "tab.activeBorder": "#909090"
    }
}
```

I have `.vscode` directories with default settings littered all over because of this. Please only create settings if a color is specifically chosen (or if "surprise me on startup" is set, of course).

**Comment by johnpapa** [comment] 2019-07-27 01:51
What version are you using of vscode and peacock?

Peacock should not add colors (there are no defaults) unless you tell it to, at this time. (Though this may change in the future if there are enough interest in default colors.)

**Comment by benc-uk** [comment] 2019-07-27 09:02
Same here, every single project or folder I open it's creating a .vscode folder and settings.json and duplicating my colors in there. I normally have my colors set "globally" in my user/settings.json NOT per project 

It wasn't doing this previously 

I've had to disable the extension for now :(

**Comment by benc-uk** [comment] 2019-07-27 09:08
I think this regression was caused by this change in 2.5.1

https://github.com/johnpapa/vscode-peacock/commit/211602d6768c36034398c086995127f6ddb42d6d#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

**Comment by johnpapa** [comment] 2019-07-27 12:13
Can you try installing 2.5.0 and report back ?

**Comment by benc-uk** [comment] 2019-07-27 12:33
Installed 2.5.0

Found it was still creating settings.json in certain project folders not others. I ran `Peacock: Reset Colors` in those projects and it has stopped creating settings.json file now

**Comment by johnpapa** [comment] 2019-07-27 12:38
@benc-uk - are you saying the problem you are reporting is happening with 2.5.0 too?

**Comment by benc-uk** [comment] 2019-07-27 12:40
Yes it happens on 2.5.0 opening some projects, unless I run **Reset Colors**

**Comment by johnpapa** [comment] 2019-07-27 12:41
thanks ...

I'm having trouble reproducing this. Can you help clarify ... I think you are saying that if you open Peacock in a project that has no peacock colors in the workspace settings (.vscode/settings.json) that Peacock is writing colors to .vscode/settings.json. If so, that is a bug, but I cannot repro this.

Or are you saying you open one project, use Peacock and set to a color (blue), then open another project that uses Peacock and the colors are also set to blue. (color is being copied - which is undesired)

thanks for the feedback

**Comment by benc-uk** [comment] 2019-07-27 15:10
The memento thing sounds like what was happening, when Peacock v2.5.0 loaded/updated for the first time, it suddenly changed the accent/badge color (to bright magenta) and that was shown on the status bar. I don't recall being prompted to select a memento color, and it was certainly not any any of my existing settings (it clashed horribly) 

I immediately hid the prompt from the status bar but then found myself in this confusing situation

Thanks for looking into this and reverting for now

**Comment by johnpapa** [comment] 2019-07-27 15:21
The accents are a new feature which can be turned on or off in settings (see the readme and changelog).  The statusbar is just to show you what your color is. So these don't affect it.

The memento is just a variable that stores the color you select. Previously Peacock was not storing your color, now it does (in a memento).

I just republished 2.5.2. Can you try with that version and report back?

**Comment by benc-uk** [comment] 2019-07-27 15:52
On 2.5.2 - and seeing no problems

**Comment by johnpapa** [comment] 2019-07-27 15:55
Thanks @benc-uk - sorry for the pains on this and than you for helping diagnose.

I'm going to keep 2.5.2 in place for now.

The next version will refactor this logic as it is indeed likely that the memento and remote logic that are causing this.

**Comment by johnpapa** [comment] 2019-07-27 21:08
2.5.2 should resolve this (now published).

closing. if you see this again, please open an new issue. 

thanks for reporting this

**Closed by johnpapa** 2019-07-27 21:08 UTC

**Comment by MarekLew** [comment] 2019-08-20 08:06
Version 3.1.1 Creates setting.js without my permission.

**Comment by kbd** [comment] 2019-08-20 16:00
Can confirm this undesirable behavior is back with 3.1.1:

```
$ rg peacock ~/Library/Application\ Support/Code/User/settings.json
95:    "peacock.surpriseMeOnStartup": false,
96:    "peacock.affectStatusBar": false,
97:    "peacock.affectActivityBar": false,
98:    "peacock.affectAccentBorders": false,
99:    "peacock.affectTabActiveBorder": true,
100:    "peacock.favoriteColors": [
$ ls -a
./  ../
$ code .
$ ls -a
./  ../  .vscode/
$ bat --style=header,numbers .vscode/*
     File: .vscode/settings.json
   1 {
   2     "peacock.color": "#777",
   3     "workbench.colorCustomizations": {
   4         "titleBar.activeBackground": "#777777",
   5         "titleBar.inactiveBackground": "#77777799",
   6         "titleBar.activeForeground": "#e7e7e7",
   7         "titleBar.inactiveForeground": "#e7e7e799",
   8         "tab.activeBorder": "#909090"
   9     }
  10 }
```

But a new ticket should be opened.

**Comment by johnpapa** [comment] 2019-08-20 16:00
Thanks. Please open a new issue and I’ll look into it.

**Comment by jovyllebermudez** [comment] 2022-08-26 04:15
I can suggest a thing,
it is indeed an issue that our workmates might don't like their VSCode color get changed by us.

We can "disable (workspace)" this extension to the particular project/workspace, this saved me. My workmate mocked me with purple vscode getting into the production.
