### ISSUE TITLE
Where should "starter" Favorites be stored?

### ISSUE THREAD

**Issue by ffxsam** [johnpapa/vscode-peacock#242] opened 2019-08-06 16:59 UTC
**Versions (please complete the following information):**

- OS: macOS 10.14.6
- VS Code version 1.36.1
- Peacock Version 3.0.1

**Describe the bug**
At random times (maybe after an extension update?), Peacock adds in the default colors to my settings.json, and I have to go in and remove them.

**To Reproduce**
Unsure of what causes this.

**Comment by johnpapa** [comment] 2019-08-08 14:46
Yes, this is "as designed" right now.

These are the default "favorites". I understand and agree with your concern. I am tyring to figure out the best way to enhance the default favorites experience. here are the key points:

1. there are a default set of favorite colors that peacock adds
1. users can add or remove these favorites, and then customize their own
1. if new favorites are added in a new version of peacock, the set of defaults is re-added (merged)


When new favorites are added to peacock, should they be merged into each user's favorites? If not, then nobody will ever get new ones. 

is there a better way to handle favorites? Perhaps cateogrize them between baked in faves and custom faves? see #198 for details

should Peacock take baked in favorites out of the settings and instead read from an API, to stop cluttering the settings? see #213 for this idea

I'm not quite sure yet, and I am open to feedback on this

**Comment by ffxsam** [comment] 2019-08-08 16:36
I personally would leave it up to user choice. Even if there are new favorites, some of us may not want them. I'd add a new command like "Peacock: Download Stock Favorites" or something to that effect, which pops up a notice letting us know that custom colors have been added to our settings.json.

**Comment by johnpapa** [comment] 2019-08-09 00:25
> Even if there are new favorites, some of us may not want them.
agreed

> I'd add a new command like "Peacock: Download Stock Favorites" or something to that effect, which pops up a notice letting us know that custom colors have been added to our settings.json.
This command exists now and is called "Add the recommended favorites"

**Comment by willpower232** [comment] 2019-08-09 09:01
Would there be anything wrong with adding a setting allowing users to opt out of the favourites? You could always label it warning that they would not see new favourites as you add them and default it to false so new users always get the favorites so they can try out the plugin "out of the box". The plugin already copes perfectly if none are set.

**Comment by johnpapa** [comment] 2019-08-09 12:30
Yes, there could be a setting that enables or disables this. Though I am always aware that the more surface ares for settings, the greater chance of confusing how to use Peacock. So before I go to add new settings, I want to see if there are other options too.

One of the reasons the new faves are an issue is because of how new ones are being added. If that model changes to where none of "baked in" favorites are stored in settings, then this is all a non issue. This is why I am considering #198 for categorization.

This is all good feedback.

**Comment by johnpapa** [comment] 2019-08-13 13:56
fixed by #252

**Comment by johnpapa** [comment] 2019-08-22 13:10
fixedfixed by #252

**Closed by johnpapa** 2019-08-22 13:10 UTC
