### ISSUE TITLE
Peacock automattically overrides settings.json without authorization.

### ISSUE THREAD

**Issue by tomByrer** [johnpapa/vscode-peacock#306] opened 2019-11-13 17:25 UTC
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
OS: Windows_NT x64 10.0.18362
Peacock: v3.2.0

**Describe the bug**
1: Edit & save `settings.json` outside of VSCode with all VSCode sessions closed (eg manually customize "statusBar.foreground")
2: Open project in VSCode
3. The manually customized settings will load for a split second, but then Peacock will over write my settings.

Was to be a fix action for #293

**Comment by johnpapa** [comment] 2019-11-14 16:07
Is this due to the alpha in #293 ?

if not, please clarify the difference

**Comment by musicfuel** [comment] 2019-11-14 16:09
@tomByrer I think what you are saying is that you use Peacock to change the colors (or you change them manually outside VS Code using the `workspace.colorCustomizations` properties to tweak colors to your liking. However, the next time you open VS Code those changes are overridden by the initialization of Peacock, is that right? Does your file that you are trying to change also have the `peacock.color` key in it?

**Comment by musicfuel** [comment] 2019-11-14 16:15
My guess is there is some aspect of the memento migration falling through to the end case where the derived color is being used and overwriting user-defined settings that peacock may or may not have defined.

https://github.com/johnpapa/vscode-peacock/blob/a00dda743d1639d562ac6461f6669e998ce317ef/src/migration.ts#L51

**Comment by tomByrer** [comment] 2019-11-15 02:00
> However, the next time you open VS Code those changes are overridden by the initialization of Peacock, is that right?

Yes.
But AFAIK you can't choose any foreground colors in the VSCode Global settings (NOT the project settings).  You can only set the background, & Peacock (via an external lib it seems) auto-calculates the foreground.  Only workaround you have available is the *project* settings.json, which seems is not a workaround.

In my previous post, I made a suggestion to allow the global settings allow to manually define a foreground color, like so:
```json
"peacock.favoriteColors": [
        {
            "name": "Nord: Auroa Red",
            "value": "#bf616a4d",
            "menu": "white",
            "icon": "lemon"
        },
```

**Comment by johnpapa** [comment] 2020-01-23 13:30
I see. thanks for clarifying your point. Peacock uses the main color to reset the colors based off that main color. So when you alter one of them, then reload in vscode, it re-applies (thus changing any customizing you did).

I don't see a way (without a lot of risk) to have Peacock work and allow customizing of a single property like this. It is important that Peacock sets the colors based off the main color as everything is driven off that. There is no current way for Peacock to know that this one color setting should be overridden. 

Your suggestion on having Peacock store not just the main color but also the foreground (menu and icon perhaps) is interesting. This would be a major change and would permeate through many areas. I'm not willing to make this type of change at this time. However, if a detailed strategy can be laid out on how to make this work and testable, I'm open to it.

At this time I am closing this as "as designed".

**Closed by johnpapa** 2020-01-23 13:30 UTC

**Comment by segux** [comment] 2020-07-15 12:24
Hi, im getting this issue too.

Everytime i start the project, peacock sets `workbench.colorCustomizations` configuration.

Indentation is different to the original `.vscode/settings.json` and git detect it as changed file.
