### ISSUE TITLE
Peacock border settings reset / enabled every time project is opened.

### ISSUE THREAD

**Issue by mikeerickson** [johnpapa/vscode-peacock#474] opened 2021-10-16 13:47 UTC
Every time I open a project which has peacock settings, it always enables these two settings to "editorGroup.border" 

"panel.border": "#30c854",
"sideBar.border": "#30c854"

So, if I disable (remove) they always return

**Comment by mikeerickson** [comment] 2021-10-18 16:03
Well, ultimately I have disabled peacock. Are you saying this is the way it will always be moving forward and I will always Jane this situation if I want to use peacock?

**Comment by johnpapa** [comment] 2022-02-06 17:33
I can no longer reproduce this behavior since #472 .

Can anyone confirm if the behavior is still a problem?

If not, I will close this issue

**Comment by johnpapa** [comment] 2022-03-11 19:08
closing due to inactivity. if we can get confirmation with a repro, please reopen it

**Closed by johnpapa** 2022-03-11 19:08 UTC
