### ISSUE TITLE
Support for gradient

### ISSUE THREAD

**Issue by d4nielix** [johnpapa/vscode-peacock#497] opened 2022-08-10 09:06 UTC
Hi, like someone requested two years ago:
https://github.com/johnpapa/vscode-peacock/issues/338
, I would like to ask for a gradient support. Maybe it is possible in current VSC version.

EDIT: also maybe there is a possibility to add alpha parameter - number between 0.0 (fully transparent) and 1.0 (fully opaque), because I feel that some colors are too distracting.

**Comment by johnpapa** [comment] 2022-08-10 09:06
Thank you @d4nielix for creating this issue!

**Comment by willpower232** [comment] 2022-08-12 06:56
vscode does support an alpha channel which is good for personal customisations but I'm not sure how that could fit sensibly into whatever algorithm peacock uses

https://code.visualstudio.com/api/references/theme-color

**Comment by johnpapa** [comment] 2022-08-14 19:52
Currently there is no support for a gradient , for example, in the activityBar given the VS Code API.

See duplicate of #338

**Closed by johnpapa** 2022-08-14 19:52 UTC
