### ISSUE TITLE
Feature Request: Save configs separated with .vscpeacock

### ISSUE THREAD

**Issue by ZouYouShun** [johnpapa/vscode-peacock#266] opened 2019-08-22 02:37 UTC
Because we work with teams member, everyone wants to use different color with the editor, so we don't want to commit the settings.json into git.

could we separated the setting configs from `settings.json` to `.vscpeacock` file, let we can ignore the `.vscpeacock`?

like this https://github.com/leftstick/vscode-favorites

<img width="520" alt="螢幕快照 2019-08-22 上午10 35 39" src="https://user-images.githubusercontent.com/5878538/63481639-a3ac6b80-c4c8-11e9-8017-41b71e2a4fde.png">

**Comment by johnpapa** [comment] 2019-08-22 13:09
This discussion came up as part of #7 ... the problem is that while we can save them to another file, they would still have to be copied to the settings.json file for vs code to pick them up. Then removed before you push to git. You run into the same problem, unfortunately.

The best way to get traction on this issue is to add your support for it to the VSCode open issue, which you can find in #7. Currently there is no ideal way to avoid this.


closing as this is perfect for #7

**Closed by johnpapa** 2019-08-22 13:09 UTC
