### ISSUE TITLE
Keyboard shortcut for "Surprise Me with a Random Color" overwrite VSCode default for "Delete line"

### ISSUE THREAD

**Issue by supdegrave** [johnpapa/vscode-peacock#390] opened 2020-05-11 13:14 UTC
**Versions (please complete the following information):**

- OS: Mac
- VS Code Version: 1.45.0
- Peacock Version: 3.7.1

**Describe the bug**
Prior to the most recent Peacock update, Cmd+Shift+K has served as "Delete line". This is a long-standing default, as defined here: 

https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf

The following commit overwrites this keyboard shortcut: 

https://github.com/johnpapa/vscode-peacock/commit/cac7b2ae0ff1170f9764e339ac1ba7c0a8c01f47#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

This should be changed, so it doesn't stomp on a finger-familiar pre-existing setting. 

Further, holding this combination (say, in order to delete a bunch of lines) with the latest version of Peacock got stuck in "Surprise me" mode (once, I'm not going to try again), so that the colors keep strobing randomly even after releasing the keys. I had to close VSCode to stop it. 

**To Reproduce**

1. open VSCode, ensure that Peacock version 3.7.1 is installed. 
2. open a new document, add a few lines of code
3. press Cmd+Shift+K, note that app chrome color changes

**Expected behavior**

* line with cursor on it should be deleted

**Comment by johnpapa** [comment] 2020-05-11 13:14
Thank you @supdegrave for creating this issue!

**Comment by johnpapa** [comment] 2020-05-11 13:17
duplicate of #389 

Fixed in 3.7.2

**Closed by johnpapa** 2020-05-11 13:17 UTC
